// my-app/angular-app/task-manager/src/app/introduction/introduction.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-introduction',
  templateUrl: './introduction.component.html',
  styleUrls: ['./introduction.component.css'],
})
export class IntroductionComponent {
  @Input() msg!: string;
}

<div>
  <h1 class="blue">{{ msg }}</h1>
  <h3>
    Questa applicazione e stata creata con
    <a href="#" target="_blank" rel="noopener noreferrer"> Angular </a>
  </h3>
</div>

// my-app/react-app/task-manager/src/components/Introduction.js
import React from "react";
import "./Introduction.css";

function Introduction({ msg }) {
  return (
    <div>
      <h1 className="blue">{msg}</h1>
      <h3>
        Questa applicazione e stata creata con {""}
        <a href="#" target="_blank" rel="noopener">
          React
        </a>
      </h3>
    </div>
  );
}

export default Introduction;
