// my-app/angular-app/task-manager/src/app/task-item/task-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Task } from '../task.model';

@Component({
  selector: 'app-task-item',
  templateUrl: './task-item.component.html',
  styleUrls: ['./task-item.component.css'],
})
export class TaskItemComponent {
  @Input() task!: Task;
  @Output() updateTask = new EventEmitter<Task>();
  @Output() deleteTask = new EventEmitter<number>();
  @Output() toggleTask = new EventEmitter<number>();

  showEditMenu = false;
  title = '';
  description = '';
  dueDate = '';

  handleUpdateTask() {
    if (!this.title || !this.description || !this.dueDate) {
      alert('Please fill out all fields');
      return;
    }
    const updatedTask = {
      ...this.task,
      title: this.title,
      description: this.description,
      dueDate: this.dueDate,
    };
    this.updateTask.emit(updatedTask);
    this.showEditMenu = false;
  }

  handleDeleteTask() {
    this.deleteTask.emit(this.task.id);
  }

  handleToggleTask() {
    this.toggleTask.emit(this.task.id);
  }

  handleEditClick() {
    this.showEditMenu = !this.showEditMenu;
    if (this.showEditMenu) {
      this.title = this.task.title;
      this.description = this.task.description;
      this.dueDate = this.task.dueDate;
    }
  }

  arrow = 'assets/arrow.svg';
}

<div [ngClass]="{ TaskItem: true, show: showEditMenu }">
  <img
    [src]="arrow"
    alt="Arrow Icon"
    [ngClass]="{arrow, show: showEditMenu}"
    height="20"
    width="20"
  />
  <h3 class="info">{{ task.title }}</h3>
  <span class="info description">{{ task.description }}</span>
  <span class="date">{{ task.dueDate }}</span>
  <div class="button-container">
    <button (click)="handleDeleteTask()">Delete</button>
    <button (click)="handleEditClick()">Edit</button>
  </div>

  <label>Stato</label>
  <input
    type="checkbox"
    [checked]="task.completed"
    (change)="handleToggleTask()"
  />

  <div class="form-container" *ngIf="showEditMenu">
    <input type="text" [(ngModel)]="title" [value]="task.title" />
    <input type="text" [(ngModel)]="description" [value]="task.description" />
    <input type="date" [(ngModel)]="dueDate" [value]="task.dueDate" />
    <button (click)="handleUpdateTask()">Update</button>
  </div>
</div>

// my-app/react-app/task-manager/src/components/TaskItem.js
import React, { useState } from "react";

import "./TaskItem.css";
import arrow from "../images/arrow.svg";

function TaskItem({ task, onUpdateTask, onDeleteTask, onToggleTask }) {
  const [showEditMenu, setShowEditMenu] = useState(false);

  function handleUpdateTask(event) {
    event.preventDefault();
    const title = event.target.title.value;
    const description = event.target.description.value;
    const dueDate = event.target.dueDate.value;
    if (!title || !description || !dueDate) {
      alert("Please fill out all fields");
      return;
    }
    const updatedTask = {
      ...task,
      title,
      description,
      dueDate,
    };
    onUpdateTask(task.id, updatedTask);
    setShowEditMenu(false);
  }

  function handleDeleteTask() {
    onDeleteTask(task.id);
  }

  function handleToggleTask() {
    onToggleTask(task.id);
  }

  function handleEditClick() {
    setShowEditMenu(!showEditMenu);
  }

  return (
    <li>
      <div className={`TaskItem ${showEditMenu ? "show" : ""}`}>
        <img
          src={arrow}
          alt="Arrow Icon"
          className={`arrow ${showEditMenu ? "show" : ""}`}
          height={20}
          width={20}
        />
        <h3 className="info">{task.title}</h3>
        <span className="info description">{task.description}</span>
        <span className="date">{task.dueDate}</span>
        <div className="button-container">
          <button onClick={handleDeleteTask}>Delete</button>
          <button onClick={handleEditClick}>Edit</button>
        </div>

        <label>Stato</label>
        <input
          type="checkbox"
          checked={task.completed}
          onChange={handleToggleTask}
        />

        {showEditMenu && (
          <form
            className={`form-container ${showEditMenu ? "show" : ""}`}
            onSubmit={handleUpdateTask}
          >
            <input type="text" name="title" defaultValue={task.title} />
            <input
              type="text"
              name="description"
              defaultValue={task.description}
            />
            <input type="date" name="dueDate" defaultValue={task.dueDate} />
            <button type="submit">Update</button>
          </form>
        )}
      </div>
    </li>
  );
}

export default TaskItem;
