// my-app/angular-app/task-manager/src/app/task-form/task-form.component.ts
import { Component, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-task-form',
  templateUrl: './task-form.component.html',
  styleUrls: ['./task-form.component.css'],
})
export class TaskFormComponent {
  @Output() addTask = new EventEmitter<any>();

  title = '';
  description = '';
  dueDate = '';

  handleSubmit() {
    if (!this.title || !this.description || !this.dueDate) {
      alert('Please fill out all fields');
      return;
    }
    const newTask = {
      id: Date.now(),
      title: this.title,
      description: this.description,
      dueDate: this.dueDate,
      completed: false,
    };
    this.addTask.emit(newTask);
    this.title = '';
    this.description = '';
    this.dueDate = '';
  }
}

<form class="TaskForm" (ngSubmit)="handleSubmit()">
  <input
    type="text"
    placeholder="Titolo"
    [(ngModel)]="title"
    name="title"
    required
  />
  <input
    type="text"
    placeholder="Descrizione"
    [(ngModel)]="description"
    name="description"
    required
  />
  <input
    type="date"
    placeholder="Data di scadenza"
    [(ngModel)]="dueDate"
    name="dueDate"
    required
  />
  <button type="submit">Add task</button>
</form>

// my-app/react-app/task-manager/src/components/TaskForm.js
import React, { useState } from "react";

import "./TaskForm.css";

function TaskForm({ onAddTask }) {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [dueDate, setDueDate] = useState("");

  function handleSubmit(event) {
    event.preventDefault();
    const task = {
      id: Date.now(),
      title,
      description,
      dueDate,
      completed: false,
    };
    onAddTask(task);
    setTitle("");
    setDescription("");
    setDueDate("");
  }

  return (
    <form className="TaskForm" onSubmit={handleSubmit}>
      <input
        type="text"
        placeholder="Titolo"
        value={title}
        onChange={(event) => setTitle(event.target.value)}
      />
      <input
        type="text"
        placeholder="Descrizione"
        value={description}
        onChange={(event) => setDescription(event.target.value)}
      />
      <input
        type="date"
        placeholder="Data di scadenza"
        value={dueDate}
        onChange={(event) => setDueDate(event.target.value)}
      />
      <button type="submit">Add task</button>
    </form>
  );
}

export default TaskForm;
