// my-app/angular-app/task-manager/src/app/task-manager/task-manager.component.ts
import { Component } from '@angular/core';
import { Task } from '../task.model';

@Component({
  selector: 'app-task-manager',
  templateUrl: './task-manager.component.html',
  styleUrls: ['./task-manager.component.css'],
})
export class TaskManagerComponent {
  tasks: Task[] = [
    {
      id: 0,
      title: 'Learn Angular',
      description: 'Learn how to use Angular',
      dueDate: '2021-03-01',
      completed: true,
    },
  ];

  addTask(task: Task) {
    this.tasks = [...this.tasks, task];
  }
}

<div class="TaskManager">
  <h1>Task Manager</h1>
  <app-task-form (addTask)="addTask($event)"></app-task-form>
  <app-task-list [tasks]="tasks"></app-task-list>
</div>

// my-app/react-app/task-manager/src/components/TaskManager.js
import React, { useState } from "react";
import TaskList from "./TaskList";
import TaskForm from "./TaskForm";

import "./TaskManager.css";

function TaskManager() {
  function addTask(task) {
    setTasks([...tasks, task]);
  }

  const [tasks, setTasks] = useState([
    {
      id: 0,
      title: "Learn React",
      description: "Learn how to use React",
      dueDate: "2021-03-01",
      completed: true,
    },
  ]);

  function updateTask(id, updatedTask) {
    setTasks(tasks.map((task) => (task.id === id ? updatedTask : task)));
  }

  function deleteTask(id) {
    setTasks(tasks.filter((task) => task.id !== id));
  }

  function toggleTask(id) {
    setTasks(
      tasks.map((task) =>
        task.id === id ? { ...task, completed: !task.completed } : task
      )
    );
  }

  return (
    <div className="TaskManager">
      <h1>Task Manager</h1>
      <TaskForm onAddTask={addTask} />
      <TaskList
        tasks={tasks}
        onUpdateTask={updateTask}
        onDeleteTask={deleteTask}
        onToggleTask={toggleTask}
      />
    </div>
  );
}

export default TaskManager;
