// my-app/react-app/task-manager/src/App.js
import React from "react";
import logo from "./images/React-icon.svg";

import {
  createBrowserRouter,
  RouterProvider,
  Routes,
  Route,
} from "react-router-dom";
import {} from "react-router-dom";

import "./App.css";
import Introduction from "./components/Introduction";
import TaskManager from "./components/TaskManager";
import About from "./components/About";

const router = createBrowserRouter([
  {
    path: "/",
    element: <TaskManager />,
  },
  {
    path: "/about",
    element: <About />,
  },
]);

function App() {
  return (
    <div className="App">
      <header>
        <img src={logo} alt="React logo" className="logo" />
        <div className="wrapper">
          <Introduction msg={"React"} />
          <nav>
            <a href="/">Task Manager</a>
            <a href="/about">Presentazione</a>
          </nav>
        </div>
      </header>
      <div className="wrapper">
        <RouterProvider router={router}>
          <Routes>
            <Route path="/" element={<TaskManager />} />
            <Route path="/about" element={<About />} />
          </Routes>
        </RouterProvider>
      </div>
    </div>
  );
}

export default App;

// my-app/angular-app/task-manager/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'task-manager';
}

<div class="App">
  <header>
    <img
      alt="Vue logo"
      class="angular logo"
      src="./assets/angular.svg"
      width="125"
      height="125"
    />
    <div class="wrapper">
      <app-introduction [msg]="'Angular'"></app-introduction>
      <nav>
        <a routerLink="/">Task Manager</a>
        <a routerLink="/about">Presentazione</a>
      </nav>
    </div>
  </header>
  <div class="wrapper">
    <router-outlet></router-outlet>
  </div>
</div>
