// my-app/react-app/task-manager/src/components/TaskList.js
import React from "react";
import TaskItem from "./TaskItem";

function TaskList({ tasks, onUpdateTask, onDeleteTask, onToggleTask }) {
  return (
    <ul>
      {tasks.map((task) => (
        <TaskItem
          key={task.id}
          task={task}
          onUpdateTask={onUpdateTask}
          onDeleteTask={onDeleteTask}
          onToggleTask={onToggleTask}
        />
      ))}
    </ul>
  );
}

export default TaskList;

// my-app/vue-app/task-manager/src/components/TaskList.vue
<template>
  <ul>
    <TaskItem
      v-for="task in tasks"
      :key="task.id"
      :task="task"
      @updateTask="onUpdateTask"
      @deleteTask="onDeleteTask"
      @toggleTask="onToggleTask"
    />
  </ul>
</template>

<script>
import TaskItem from "./TaskItem.vue";

export default {
  name: "TaskList",
  components: {
    TaskItem,
  },
  props: {
    tasks: {
      type: Array,
      required: true,
    },
  },
  methods: {
    onUpdateTask(task) {
      this.$emit("updateTask", task);
    },
    onDeleteTask(task) {
      this.$emit("deleteTask", task);
    },
    onToggleTask(task) {
      this.$emit("toggleTask", task);
    },
  },
};
</script>
